
version: "3.8"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    network_mode: bridge
    hostname: gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=#YOUR_IP_HERE
      - VPN_ENDPOINT_PORT=#YOUR_PORT_HERE
      - WIREGUARD_PUBLIC_KEY=#YOUR_PUBLIC_KEY_HERE
      - WIREGUARD_PRIVATE_KEY=#YOUR_PRIVATE_KEY_HERE
      - WIREGUARD_ADDRESSES=#YOUR_WG_ADDRESS_HERE
    volumes:
      - /opt/gluetun/config:/gluetun
    ports:
      - 8112:8112 # Deluge Web-UI
      - 6881:6881 # Deluge
      - 6881:6881/udp # Deluge
      - 8081:8081 # Joal
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DELUGE_LOGLEVEL=error # optional
    volumes:
      - /opt/deluge/config:/config
      - /opt/deluge/downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - AUTO_UPDATE=true # optional
    volumes:
      - /opt/jackett/config:/config
      - /opt/deluge/downloads:/downloads
    ports:
      - 9117:9117
    depends_on:
      - gluetun
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /opt/radarr/config:/config
      - /nfsmount/plexmediaserver:/movies
      - /opt/deluge/downloads:/downloads
    ports:
      - 7878:7878
    depends_on:
      - gluetun
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /opt/sonarr/config:/config
      - /nfsmount/plexmediaserver:/tv
      - /opt/deluge/downloads:/downloads
    ports:
      - 8989:8989
    depends_on:
      - gluetun
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /opt/tautulli/config:/config
    ports:
      - 8181:8181
    depends_on:
      - gluetun
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Paris
    ports:
      - 8191:8191
    depends_on:
      - gluetun
    restart: unless-stopped

  joal:
    image: anthonyraymond/joal:latest
    container_name: joal
    network_mode: "service:gluetun"
    volumes:
      - /opt/joal/config:/data
    depends_on:
      - gluetun
    restart: unless-stopped
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=8081", "--joal.ui.path.prefix=joal", "--joal.ui.secret-token=yourtokenhere"]

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /opt/overseerr/config:/config
    ports:
      - 5055:5055
    depends_on:
      - gluetun
    restart: unless-stopped
